#!/data/data/com.termux/files/usr/bin/bash

set -e

msg() {
    echo -e "$@"
}

info() {
    printf "\033[1;33m$@\033[0m\n"
}

success() {
    printf "\033[0;32m$@\033[0m\n"
}

fail() {
    printf "\033[0;31m$@\033[0m\n"
    exit 1
}

proot_exec() {
    proot-distro login ubuntu -- eval "$1"
}

ROOT_MODE=0
USE_UBUNTU20=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --root)
            ROOT_MODE=1
            ;;
        --ubuntu20)
            USE_UBUNTU20=1
            ;;
        --help)
            msg "Usage: $0 [--root] [--ubuntu20]"
            exit 0
            ;;
        *)
            fail "invalid arguements provided"
            ;;
    esac
    shift
done

if [[ $USE_UBUNTU20 -eq 1 ]]; then
    UBUNTU_VERSION="20.04"
    ROOTFS_TAR="ubuntu-focal-core-cloudimg-arm64-root-2020.12.10.tar.gz"
    ROOTFS_URL="https://github.com/termux/proot-distro/releases/download/v1.2-ubuntu-focal-rootfs/$ROOTFS_TAR"
else
    UBUNTU_VERSION="24.04"
    ROOTFS_TAR="noble-server-cloudimg-arm64-root.tar.xz"
    ROOTFS_URL="https://cloud-images.ubuntu.com/noble/current/$ROOTFS_TAR"
fi

add_to_file() {
    grep -qF -- "$1" "$2" || echo "$1" >> "$2"
}

base_setup() {
    termux-wake-lock

    yes | termux-setup-storage

    pkg install -y proot-distro termux-api net-tools openssh wget tmux

    TERMUX_API_APK_URL='https://f-droid.org/repo/com.termux.api_51.apk'
    wget -q --show-progress --no-clobber --tries=5 $TERMUX_API_APK_URL -P /sdcard/flowpilot/Downloads

    # Optional: add your own installer URL or copy manually
    #INSTALL_SCRIPT_URL='https://example.com/install-bluepilot-android'
    #wget -q --show-progress --tries=5 $INSTALL_SCRIPT_URL -O /sdcard/flowpilot/Downloads/install-bluepilot-android

    add_to_file 'sshd' ~/.bashrc
    add_to_file 'termux-wake-lock' ~/.bashrc

    sed -i '/allow-external-apps/s/^#*//g' $HOME/.termux/termux.properties
}

download_rootfs() {
    mkdir -p /sdcard/flowpilot/Downloads
    if ! wget --show-progress --tries=5 "$ROOTFS_URL" -P /sdcard/flowpilot/Downloads/; then
        fail "failed to download rootfs from $ROOTFS_URL"
    fi
}

extract_rootfs() {
    local archive="$1"
    local dest="$2"
    local log_file
    log_file="$(mktemp)"

    set +e
    tar xfp "$archive" -C "$dest" \
        --no-same-owner --no-same-permissions --numeric-owner \
        --exclude='dev/*' --hard-dereference 2>"$log_file"
    tar_status=$?
    set -e

    if [[ $tar_status -ne 0 ]]; then
        if grep -qv -e "Cannot hard link" -e "Exiting with failure status" "$log_file"; then
            cat "$log_file"
            rm -f "$log_file"
            fail "rootfs extraction failed"
        fi
    fi
    rm -f "$log_file"

    if [[ ! -x "$dest/bin/bash" ]]; then
        fail "rootfs extraction incomplete: missing /bin/bash"
    fi
}

setup_nonroot_env() {
    info "Preparing to install bluepilot non-root env ..."

    rm -f /data/data/com.termux/files/usr/bin/login-bluepilot

    CHROOT="$HOME/bluepilot_env_ubuntu${UBUNTU_VERSION//./}"
    mkdir -p "$CHROOT"
    download_rootfs
    extract_rootfs "/sdcard/flowpilot/Downloads/$ROOTFS_TAR" "$CHROOT"

    echo "#!/data/data/com.termux/files/usr/bin/bash

    mkdir -p $CHROOT/sdcard

    unset LD_PRELOAD
    command=\"proot\"
    command+=\" --link2symlink\"
    command+=\" -r $CHROOT\"
    command+=\" -b /dev\"
    command+=\" -b /proc\"
    command+=\" -b /sys\"
    command+=\" -b $CHROOT/tmp:/dev/shm\"
    command+=\" -b /data/data/com.termux\"
    command+=\" -b /sdcard\"
    command+=\" -b /mnt\"
    command+=\" -w /root\"
    command+=\" /usr/bin/env -i\"
    command+=\" HOME=/root\"
    command+=\" PATH=/usr/local/sbin:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/games:/usr/local/games\"
    command+=\" TERM=\$TERM\"
    command+=\" LANG=C.UTF-8\"
    command+=\" /bin/bash --login\"
    com=\"\$@\"
    if [ -z \"\$1\" ];then
        exec \$command
    else
        \$command -c \"\$com\"
    fi
    " >> /data/data/com.termux/files/usr/bin/login-bluepilot
    chmod +x /data/data/com.termux/files/usr/bin/login-bluepilot

    ln -rsf "$CHROOT" "$HOME/bluepilot_env"

    echo -e "sshd \ntermux-wake-lock \nlogin-bluepilot \"cd bluepilot && ./launch_bluepilot.sh\"" > $HOME/boot_bluepilot
    chmod +x $HOME/boot_bluepilot

    success "Bluepilot non-root environment installed ($UBUNTU_VERSION)! login with 'login-bluepilot'"
}

setup_root_env() {
    info "Preparing to install bluepilot root env ..."
    pkg install tsu
    download_rootfs

    CHROOT="$HOME/bluepilot_env_ubuntu${UBUNTU_VERSION//./}_root"
    mkdir -p "$CHROOT"
    extract_rootfs "/sdcard/flowpilot/Downloads/$ROOTFS_TAR" "$CHROOT"

    rm -f /data/data/com.termux/files/usr/bin/login-bluepilot-root
    echo "#!/data/data/com.termux/files/usr/bin/bash

    mkdir -p $CHROOT/sdcard

    mount -o remount,dev,suid /data

    unset LD_PRELOAD
    command=\"proot\"
    command+=\" --link2symlink\"
    command+=\" -0\"
    command+=\" -r $CHROOT\"
    command+=\" -b /dev\"
    command+=\" -b /proc\"
    command+=\" -b /sys\"
    command+=\" -b $CHROOT/tmp:/dev/shm\"
    command+=\" -b /data/data/com.termux\"
    command+=\" -b /:/host-rootfs\"
    command+=\" -b /sdcard\"
    command+=\" -b /mnt\"
    command+=\" -w /root\"
    command+=\" /usr/bin/env -i\"
    command+=\" HOME=/root\"
    command+=\" PATH=/usr/local/sbin:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/games:/usr/local/games\"
    command+=\" TERM=\$TERM\"
    command+=\" LANG=C.UTF-8\"
    command+=\" /bin/bash --login\"
    com=\"\$@\"
    if [ -z \"\$1\" ];then
        exec \$command
    else
        \$command -c \"\$com\"
    fi
    " >> /data/data/com.termux/files/usr/bin/login-bluepilot-root
    chmod +x /data/data/com.termux/files/usr/bin/login-bluepilot-root

    echo -e "sshd \ntermux-wake-lock \nsudo login-bluepilot-root \"cd bluepilot && ./launch_bluepilot.sh\"" > $HOME/boot_bluepilot
    chmod +x $HOME/boot_bluepilot

    success "Bluepilot root environment installed ($UBUNTU_VERSION). login with 'sudo login-bluepilot-root'"
}

if [[ $ROOT_MODE -eq 1 ]]; then
    base_setup
    setup_root_env
else
    base_setup
    setup_nonroot_env
fi
